# default.yml controls global settings and policies/queries that run on all hosts ("All teams").

policies:
queries:
agent_options:
controls:
labels: 
  - path: /Users/pedro.obando/Documents/GitHub/nicaragua-gitops-workshop/lib/all/labels/global-label.yml
org_settings:
  server_settings:
    server_url: $FLEET_URL
  fleet_desktop:
    transparency_url: https://remitly.com
  host_expiry_settings:
    host_expiry_enabled: true
    host_expiry_window: 30
  webhook_settings:
    activities_webhook:
      enable_activities_webhook: true
      destination_url: https://webhook.site/e857e290-b055-4320-9b9f-c95cc756f8a9
  org_info:
    org_name: Fleet
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
